[project]
name = "single-view-3d"
version = "0.1.0"
description = "Experiments for constrained 3D reconstruction from a single view of a scene"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "opencv-python>=4.11.0.86",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
